name: CI Pipeline Margarita

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main ]

jobs:
  all-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          playwright install --with-deps

      # Запуск сервера в фоне, чтобы тесты могли к нему обращаться
      - name: Start Server
        run: |
          uvicorn main:app --host 127.0.0.1 --port 8000 &
          sleep 5

      # 1. Запуск Unit-тестов (из твоей 2-й лабы)
      - name: Run Unit Tests
        run: pytest tests/test_unit.py --alluredir=allure-results

      # 2. Запуск BDD тестов (твоя 4-я лаба с Behave)
      - name: Run BDD Tests
        run: behave features/ticket.feature

      # 3. Запуск UI тестов (твоя 5-я лаба с Playwright)
      - name: Run UI Tests
        run: pytest tests/test_ui.py --alluredir=allure-results

      # Загрузка отчетов
      - name: Upload Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results/